// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs_CBpN45zGgCLrV8KECLTzRm6bu6B_IA',
    appId: '1:194910337403:web:64bb28344db4b5487f25de',
    messagingSenderId: '194910337403',
    projectId: 'example-235b5',
    authDomain: 'example-235b5.firebaseapp.com',
    storageBucket: 'example-235b5.firebasestorage.app',
    measurementId: 'G-5P78GFMQ2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqZxdvheitAHb2EqUHew9cz8EvgfMeyak',
    appId: '1:194910337403:android:721b1f1c732014fe7f25de',
    messagingSenderId: '194910337403',
    projectId: 'example-235b5',
    storageBucket: 'example-235b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Xqmd4uT5tbmVbbD6maCgNbEZS_LjWjo',
    appId: '1:194910337403:ios:ef5b22b330359caf7f25de',
    messagingSenderId: '194910337403',
    projectId: 'example-235b5',
    storageBucket: 'example-235b5.firebasestorage.app',
    iosBundleId: 'com.example.smthg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Xqmd4uT5tbmVbbD6maCgNbEZS_LjWjo',
    appId: '1:194910337403:ios:ef5b22b330359caf7f25de',
    messagingSenderId: '194910337403',
    projectId: 'example-235b5',
    storageBucket: 'example-235b5.firebasestorage.app',
    iosBundleId: 'com.example.smthg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs_CBpN45zGgCLrV8KECLTzRm6bu6B_IA',
    appId: '1:194910337403:web:18ea4f96d2154d687f25de',
    messagingSenderId: '194910337403',
    projectId: 'example-235b5',
    authDomain: 'example-235b5.firebaseapp.com',
    storageBucket: 'example-235b5.firebasestorage.app',
    measurementId: 'G-CC8F3KMBJW',
  );

}